[package]
name = "rust-test-app"
version = "0.1.0"
authors = ["Josh Adkins <adkinsjd@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
